### ISSUE TITLE
联想LenovoS860e  Android4.4.2  翻转镜头闪退

### ISSUE THREAD

**Issue by forcastiel** [ksvc/KSYMediaPlayer_Android#12]
E/cjx: loadPluginBriefList
                                        java.io.FileNotFoundException: /data/data/com.lenovo.ideafriend/files/pluginlist.xml: open failed: ENOENT (No such file or directory)
                                            at libcore.io.IoBridge.open(IoBridge.java:409)
                                            at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                            at android.app.ContextImpl.openFileInput(ContextImpl.java:814)
                                            at android.content.ContextWrapper.openFileInput(ContextWrapper.java:204)
                                            at com.lenovo.ideafriend.utils.pluginmanager.PluginModel.readFileData(PluginModel.java:534)
                                            at com.lenovo.ideafriend.utils.pluginmanager.PluginModel.loadPluginBriefList(PluginModel.java:484)
                                            at com.lenovo.ideafriend.utils.pluginmanager.PluginModel.initPlugins(PluginModel.java:121)
                                            at com.lenovo.ideafriend.contacts.ContactsApplication.refreshPluginList(ContactsApplication.java:306)
                                            at com.lenovo.ideafriend.contacts.ContactsApplication$1.run(ContactsApplication.java:278)
                                            at java.lang.Thread.run(Thread.java:841)
                                         Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
                                            at libcore.io.Posix.open(Native Method)
                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
                                            at libcore.io.IoBridge.open(IoBridge.java:393)
                                            at java.io.FileInputStream.<init>(FileInputStream.java:78) 
                                            at android.app.ContextImpl.openFileInput(ContextImpl.java:814) 
                                            at android.content.ContextWrapper.openFileInput(ContextWrapper.java:204) 
                                            at com.lenovo.ideafriend.utils.pluginmanager.PluginModel.readFileData(PluginModel.java:534) 
                                            at com.lenovo.ideafriend.utils.pluginmanager.PluginModel.loadPluginBriefList(PluginModel.java:484) 
                                            at com.lenovo.ideafriend.utils.pluginmanager.PluginModel.initPlugins(PluginModel.java:121) 
                                            at com.lenovo.ideafriend.contacts.ContactsApplication.refreshPluginList(ContactsApplication.java:306) 
                                            at com.lenovo.ideafriend.contacts.ContactsApplication$1.run(ContactsApplication.java:278) 
                                            at java.lang.Thread.run(Thread.java:841)

**Comment by FirmianaRain** [comment]
请问这个问题跟SDK有什么关系呢？
从日志上看，似乎没看到关于SDK的日志信息
