### ISSUE TITLE
一打开项目，直接就挂掉了

### ISSUE THREAD

**Issue by yanchunlan** [ksvc/KSYMediaPlayer_Android#167]
debug 信息如下：
java.lang.UnsatisfiedLinkError: No implementation found for void com.ksyun.media.player.KSYMediaPlayer.native_finalize() (tried Java_com_ksyun_media_player_KSYMediaPlayer_native_1finalize and Java_com_ksyun_media_player_KSYMediaPlayer_native_1finalize__)
                                                         at com.ksyun.media.player.KSYMediaPlayer.native_finalize(Native Method)
                                                         at com.ksyun.media.player.KSYMediaPlayer.finalize(KSYMediaPlayer.java:2140)
                                                         at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                         at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                         at java.lang.Thread.run(Thread.java:761)

catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ghoome.g1/com.ghoome.g1.ui.module.live.pull.main.LivePullActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.ksyun.media.player.KSYTextureView
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by FirmianaRain** [comment]
没找到Native方法的定义，应该是混淆时没添加以下语句
```
-keep class com.ksyun.media.player.**{ *; }
-keep class com.ksy.statlibrary.**{ *;}
```
