### ISSUE TITLE
2.5.0KSYMediaPlayer异常

### ISSUE THREAD

**Issue by ESC-LIC** [ksvc/KSYMediaPlayer_Android#209]
java.lang.ArithmeticException: divide by zero at com.ksyun.media.player.KSYMediaPlayer.h(KSYMediaPlayer.java:1429) at com.ksyun.media.player.KSYMediaPlayer.access$600(KSYMediaPlayer.java:82) java.lang.ArithmeticException: divide by zero at com.ksyun.media.player.KSYMediaPlayer.h(KSYMediaPlayer.java:1429) at com.ksyun.media.player.KSYMediaPlayer.access$600(KSYMediaPlayer.java:82) at com.ksyun.media.player.KSYMediaPlayer$b.handleMessage(KSYMediaPlayer.java:2160) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:156) at android.app.ActivityThread.main(ActivityThread.java:6524) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by FirmianaRain** [comment]
我们会尽快分析这个问题
