### ISSUE TITLE
android studio 播放时报这个异常 No implementation found for void com.ksyun.media.player.KSYMediaPlayer.native_init() 

### ISSUE THREAD

**Issue by jamesliuguo** [ksvc/KSYMediaPlayer_Android#234]
E/KSY_ANDROID_LOG: MediaPlayerVideoView release cost :0
E/art: No implementation found for void com.ksyun.media.player.KSYMediaPlayer.native_init() (tried Java_com_ksyun_media_player_KSYMediaPlayer_native_1init and Java_com_ksyun_media_player_KSYMediaPlayer_native_1init__)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.showlive.lbw.app, PID: 15778
                  java.lang.UnsatisfiedLinkError: No implementation found for void com.ksyun.media.player.KSYMediaPlayer.native_init() (tried Java_com_ksyun_media_player_KSYMediaPlayer_native_1init and Java_com_ksyun_media_player_KSYMediaPlayer_native_1init__)
                      at com.ksyun.media.player.KSYMediaPlayer.native_init(Native Method)
                      at com.ksyun.media.player.KSYMediaPlayer.initNativeOnce(KSYMediaPlayer.java:387)
                      at com.ksyun.media.player.KSYMediaPlayer.b(KSYMediaPlayer.java:484)
                      at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:455)
                      at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:82)
                      at com.ksyun.media.player.KSYMediaPlayer$Builder.build(KSYMediaPlayer.java:422)
                      at com.ksy.media.widget.videoview.MediaPlayerVideoView.openVideo(MediaPlayerVideoView.java:261)
                      at com.ksy.media.widget.videoview.MediaPlayerVideoView.access$1800(MediaPlayerVideoView.java:40)
                      at com.ksy.media.widget.videoview.MediaPlayerVideoView$8.surfaceCreated(MediaPlayerVideoView.java:534)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:632)
                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2247)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6401)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:688)
                      at android.view.Choreographer.doFrame(Choreographer.java:623)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
                      at android.os.Handler.handleCallback(Handler.java:754)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:163)
                      at android.app.ActivityThread.main(ActivityThread.java:6205)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
I/Process: Sending signal. PID: 15778 SIG: 9

**Comment by dengchu817** [comment]
机型，android版本号是多少呢

**Comment by jamesliuguo** [comment]
红米 4x   android studio 3.01   sdk 26

**Comment by jamesliuguo** [comment]
libksyplayer.jar	push KSYMediaplayer_a2.2.1.2	3 days ago
libksystat.jar	update sdk to v2.0.3

**Comment by ilvelh** [comment]
jamesliuguo 这个问题你解决了吗？我也遇到了

**Comment by KongGuoguang** [comment]
sourceSets.main {
        jniLibs.srcDirs 'src/main/libs' // 动态库和jar的存放路径
        jni.srcDirs = [] // This prevents the auto generation of Android.mk
    }


看下你的库文件路径是否跟gradle里面配置的一致
