### ISSUE TITLE
打开视频直播界面提示找不到jni

### ISSUE THREAD

**Issue by 121104115wyb** [ksvc/KSYMediaPlayer_Android#264]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.yc.sqt, PID: 9876
                  java.lang.UnsatisfiedLinkError: No implementation found for java.util.List com.ksyun.media.streamer.util.StringWrapper.getStringList() (tried Java_com_ksyun_media_streamer_util_StringWrapper_getStringList and Java_com_ksyun_media_streamer_util_StringWrapper_getStringList__)
                      at com.ksyun.media.streamer.util.StringWrapper.getStringList(Native Method)
                      at com.ksyun.media.streamer.util.StringWrapper.<init>(StringWrapper.java:42)
                      at com.ksyun.media.streamer.util.StringWrapper.getInstance(StringWrapper.java:24)
                      at com.ksyun.media.streamer.logstats.StatsLogReport.<init>(StatsLogReport.java:183)
                      at com.ksyun.media.streamer.logstats.StatsLogReport.getInstance(StatsLogReport.java:161)
                      at com.ksyun.media.streamer.kit.KSYStreamer.<init>(KSYStreamer.java:160)
                      at com.sugon.library.ui.CameraActivity.onCreate(CameraActivity.java:214)
                      at android.app.Activity.performCreate(Activity.java:6915)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6523)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

android 8.0 华为nava2s
android 7.0 华为荣耀v8

报错的原因是把这部分集成代码集成进我们原来的项目中，然后单独把这部分代码copy出来是可以运行的，不知道是不是与我们原来的项目有什么冲突吗

**Comment by 121104115wyb** [comment]
该问题已经解决，原来项目中引用的argis地图服务，设置了ndk

 ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi','armeabi-v7a'
        }
并没有设置支持armeabi-v7
导致 implementation 'com.ksyun.media:libksylive-armv7a:2.4.3' 引用失败，不知是不是这个原因，但我就是这么解决的，嘿嘿
