### ISSUE TITLE
demo 直接闪退

### ISSUE THREAD

**Issue by smallgirl** [ksvc/KSYMediaPlayer_Android#283]
11-15 12:43:15.897 1348-2628/? E/JobSchedulerService: jobid:20536
    java.lang.IllegalStateException: Same jobid in systemuid.
        at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:710)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:1904)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
        at com.android.server.backup.FullBackupJob.schedule(FullBackupJob.java:52)
        at com.android.server.backup.BackupManagerService$4.run(BackupManagerService.java:5417)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
11-15 12:43:16.750 531-5797/? E/msm8974_platform: platform_check_backends_match: Invalid snd_device = 
11-15 12:43:16.756 531-5797/? E/msm8974_platform: platform_get_snd_device_backend_index: BE DAI Name Table is not present
11-15 12:43:16.756 531-5797/? E/audio_hw_utils: send_app_type_cfg_for_device: Couldn't get the backend index for snd device speaker ret=-14
11-15 12:43:16.759 549-603/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
11-15 12:43:16.936 549-603/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
     return value 2
11-15 12:43:19.173 549-603/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
     return value 2
11-15 12:43:30.043 1840-2690/com.ksyun.player.demo E/KSYMediaPlayer: moov atom not found
    KSYProbe: avformat_open_input failed!
11-15 12:43:30.519 1840-2702/com.ksyun.player.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x14 in tid 2702 (AsyncTask #3)
11-15 12:43:30.583 2715-2715/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-15 12:43:30.584 2715-2715/? A/DEBUG: Build fingerprint: 'OnePlus/OnePlus3/OnePlus3T:8.0.0/OPR1.170623.032/06151230:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    pid: 1840, tid: 2702, name: AsyncTask #3  >>> com.ksyun.player.demo <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x14
    Cause: null pointer dereference
        x0   0000007ee4d67c00  x1   0000000000000000  x2   0000000000000000  x3   0000000000000000
        x4   0000000000000500  x5   0000000000000000  x6   0000007ee46a7400  x7   0000000000000004
        x8   00000000ffffffff  x9   0000000000000000  x10  0000000000000005  x11  0000000000000010
        x12  0000007ee31b7a68  x13  0000000000000000  x14  0000007f08bf76b4  x15  0000000000000000
        x16  0000007ee26b13f0  x17  0000007f08b69bb0  x18  0000007ee2ef80c8  x19  0000000000000000
        x20  0000000000000000  x21  0000007ee4d6b400  x22  0000007ee26b1000  x23  0000000000000000
        x24  00000000000002c0  x25  0000000000000000  x26  0000000000000160  x27  00000000004c4b40
        x28  0000007ee4d67c00  x29  0000007ee2ef7ee8  x30  0000007ee219f674
        sp   0000007ee2ef7c10  pc   0000007ee219f688  pstate 0000000020000000
11-15 12:43:30.586 2715-2715/? A/DEBUG: backtrace:
        #00 pc 000000000011c688  /data/app/com.ksyun.player.demo-ymv3WslMbWD87YY26ietEA==/lib/arm64/libksyplayer.so (ksy_get_thumbnail+332)
        #01 pc 0000000000102e20  /data/app/com.ksyun.player.demo-ymv3WslMbWD87YY26ietEA==/lib/arm64/libksyplayer.so
        #02 pc 000000000000f32c  /data/app/com.ksyun.player.demo-ymv3WslMbWD87YY26ietEA==/oat/arm64/base.odex (offset 0xf000)
11-15 12:43:31.756 1016-1016/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_01
11-15 12:43:31.826 1348-1706/? E/InputDispatcher: channel '79c0ddf com.ksyun.player.demo/com.ksyun.player.demo.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-15 12:43:34.396 4289-4289/? E/ContentDetectionService: updateSceneDetectionState() - No SceneDetector
11-15 12:43:35.342 532-2506/? E/vendor.qti.bluetooth@1.0-wake_lock: Release wakelock is released

**Comment by smallgirl** [comment]
替换大的so后正常，设置2倍速以后声音完全没法听，我用jikplayer编译的2倍速声音就很正常，而且同一个视频 会卡主画面，ijkplayer编译的正常
