### ISSUE TITLE
Android 9.0 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/entity/ByteArrayEntity;

### ISSUE THREAD

**Issue by aikun** [ksvc/KSYMediaPlayer_Android#292]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/entity/ByteArrayEntity;
at com.ksy.statlibrary.log.LogClient.sendRecordJson(Unknown Source:55)
at com.ksy.statlibrary.log.LogClient.sendRecord(Unknown Source:68)
at com.ksy.statlibrary.log.LogClient.access300(UnknownSource:0)atcom.ksy.statlibrary.log.LogClient1.run(Unknown Source:103)
at java.util.TimerThread.mainLoop(Timer.java:562)
at java.util.TimerThread.run(Timer.java:512)

**Comment by lijinhua** [comment]
Android 项目在运行在Android9.0上面的时候  闪退 报错如下Java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry;
解决办法：在AndroidManifest.xml文件的application标签里面加入
<uses-library android:name="org.apache.http.legacy" android:required="false" />
不明白的可以参考下图
https://www.jianshu.com/p/ea3c189f04d0
https://www.cnblogs.com/renhui/p/9796488.html

**Comment by aikun** [comment]
参考的两个方案是两个不同的问题

**Comment by aikun** [comment]
> Android 项目在运行在Android9.0上面的时候  闪退 报错如下Java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry;
> 解决办法：在AndroidManifest.xml文件的application标签里面加入
> 
> 不明白的可以参考下图
> https://www.jianshu.com/p/ea3c189f04d0
> https://www.cnblogs.com/renhui/p/9796488.html

**Comment by aikun** [comment]
上面参考的两个方案分别是两个不同的问题
这个问题是libksystat.jar在9.0日志模块NoClassDefFoundError

**Comment by zhiyou007** [comment]
@dengchu817 9.0闪退啊，apache这个包已经从系统去掉了，下载SDK怎么办？赶紧做个更新

**Comment by oooo7777777** [comment]
同样的问题 求大佬解决

**Comment by SheepYang1993** [comment]
遇到一样的问题
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/entity/ByteArrayEntity;
        at com.ksy.statlibrary.log.LogClient.sendRecordJson(LogClient.java:157)
        at com.ksy.statlibrary.log.LogClient.sendRecord(LogClient.java:312)
        at com.ksy.statlibrary.log.LogClient.access$300(LogClient.java:41)
        at com.ksy.statlibrary.log.LogClient$1.run(LogClient.java:285)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
```

**Comment by mtzfactory** [comment]
I'm having the same crash... Is there any solution?
Can we disable the sendRecordJson process?

-- EDIT: possible solution:
https://www.jianshu.com/p/ea3c189f04d0
https://developer.android.com/about/versions/pie/android-9.0-changes-28
