### ISSUE TITLE
android P的问题

### ISSUE THREAD

**Issue by oooo7777777** [ksvc/KSYMediaPlayer_Android#298]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/entity/ByteArrayEntity;
        at com.ksy.statlibrary.log.LogClient.sendRecordJson(LogClient.java:158)
        at com.ksy.statlibrary.log.LogClient.sendRecord(LogClient.java:315)
        at com.ksy.statlibrary.log.LogClient.access$300(LogClient.java:43)
        at com.ksy.statlibrary.log.LogClient$1.run(LogClient.java:288)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.entity.ByteArrayEntity" on path: DexPathList[[zip file "/data/app/com.vstyle.bobobtc-Wqz4aKuebWU0eaYH-UGdHQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.vstyle.bobobtc-Wqz4aKuebWU0eaYH-UGdHQ==/lib/arm64, /data/app/com.vstyle.bobobtc-Wqz4aKuebWU0eaYH-UGdHQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

**Comment by yazhengwang** [comment]
@oooo7777777 https://blog.csdn.net/xu11236511/article/details/83411087
