### ISSUE TITLE
KSYMediaPlayer_Android Crash

### ISSUE THREAD

**Issue by ngochuu90** [ksvc/KSYMediaPlayer_Android#31]
Hi,

When I play a link in NetMediaActivty, app crash on Android L 5.0.1
This is Error log:

```
09-13 12:00:00.262 5141-5141/com.ksyun.player.demo E/CrashReport: --------------------------------------------------------------------------------------------
09-13 12:00:00.262 5141-5141/com.ksyun.player.demo E/CrashReport: --------------------------------------------------------------------------------------------
09-13 12:00:00.317 5141-5141/com.ksyun.player.demo E/art: dlopen("/data/app/com.ksyun.player.demo-2/lib/arm64/libBugly.so", RTLD_LAZY) failed: dlopen failed: "/data/app/com.ksyun.player.demo-2/lib/arm64/libBugly.so" is too small to be an ELF executable: only found 0 bytes
09-13 12:00:00.330 5141-5174/com.ksyun.player.demo E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
09-13 12:00:00.391 5141-5182/com.ksyun.player.demo E/asdasd: 0asdasdasd
09-13 12:00:00.401 5141-5184/com.ksyun.player.demo E/asdasd: 0asdasdasd
09-13 12:00:00.407 5141-5174/com.ksyun.player.demo E/WifiManager: mWifiServiceMessenger == null
09-13 12:00:00.720 5141-5196/com.ksyun.player.demo E/libEGL: cache file failed CRC check
09-13 12:00:05.026 5141-5141/com.ksyun.player.demo E/CrashReport: Java Crash Happen cause by main(1)
09-13 12:00:05.028 5141-5141/com.ksyun.player.demo E/CrashReport: 3
09-13 12:00:05.072 5141-5141/com.ksyun.player.demo E/CrashReport: stack frame :22, has cause false
09-13 12:00:05.107 5141-5141/com.ksyun.player.demo E/CrashReport: #++++++++++Record By Bugly++++++++++#
09-13 12:00:05.107 5141-5141/com.ksyun.player.demo E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
09-13 12:00:05.107 5141-5141/com.ksyun.player.demo E/CrashReport: # PKG NAME: com.ksyun.player.demo
09-13 12:00:05.108 5141-5141/com.ksyun.player.demo E/CrashReport: # APP VER: 1.0
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # LAUNCH TIME: 2016-09-13 12:00:00
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # CRASH TYPE: JAVA_CRASH
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # CRASH TIME: 2016-09-13 12:00:05
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # CRASH PROCESS: com.ksyun.player.demo
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # CRASH THREAD: main
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # REPORT ID: fdfe946d-3319-4f6a-803e-2b4cf2a1ebf4
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # CRASH DEVICE: Redmi Note 2 UNROOT
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # RUNTIME AVAIL RAM:599023616 ROM:2771267584 SD:2718838784
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # RUNTIME TOTAL RAM:1967923200 ROM:12511289344 SD:12458860544
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: # CRASH STACK: 
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ksyun.player.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ksyun.player.demo-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libksyplayer.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                      at java.lang.System.loadLibrary(System.java:989)
                                                                      at com.ksyun.media.player.KSYMediaPlayer$1.loadLibrary(KSYMediaPlayer.java:242)
                                                                      at com.ksyun.media.player.KSYMediaPlayer.loadLibrariesOnce(KSYMediaPlayer.java:260)
                                                                      at com.ksyun.media.player.KSYMediaPlayer.initPlayer(KSYMediaPlayer.java:382)
                                                                      at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:356)
                                                                      at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:76)
                                                                      at com.ksyun.media.player.KSYMediaPlayer$Builder.build(KSYMediaPlayer.java:324)
                                                                      at com.ksyun.player.demo.activity.VideoPlayerActivity.onCreate(VideoPlayerActivity.java:435)
                                                                      at android.app.Activity.performCreate(Activity.java:5975)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
09-13 12:00:05.109 5141-5141/com.ksyun.player.demo E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
09-13 12:00:07.432 6089-6089/com.ksyun.player.demo E/CrashReport: --------------------------------------------------------------------------------------------
09-13 12:00:07.432 6089-6089/com.ksyun.player.demo E/CrashReport: --------------------------------------------------------------------------------------------
09-13 12:00:07.501 6089-6089/com.ksyun.player.demo E/art: dlopen("/data/app/com.ksyun.player.demo-2/lib/arm64/libBugly.so", RTLD_LAZY) failed: dlopen failed: "/data/app/com.ksyun.player.demo-2/lib/arm64/libBugly.so" is too small to be an ELF executable: only found 0 bytes
09-13 12:00:07.527 6089-6120/com.ksyun.player.demo E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
```

**Comment by FirmianaRain** [comment]
It seems that Android do not find arm64's libksyplayer.so.
You can move libs_live/arm64-v8a/libksyplayer.so to KsyunPlayerDemo/playerlib/libs/arm64-v8a/libksyplayer.so

**Comment by ngochuu90** [comment]
Thank you for your answer.
