### ISSUE TITLE
x86 so加载报错的问题在新版修复了么

### ISSUE THREAD

**Issue by pzhangleo** [ksvc/KSYMediaPlayer_Android#44]
还是必须制定sdk小于23呢？
因为我们的app要求必须23以上，所以想知道你们修复这个问题的进度，多谢。

**Comment by pzhangleo** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.being.fame-1/lib/x86/libksylive.so: has text relocations
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1530)
	at com.ksyun.media.player.KSYMediaPlayer$1.loadLibrary(KSYMediaPlayer.java:250)
	at com.ksyun.media.player.KSYMediaPlayer.loadLibrariesOnce(KSYMediaPlayer.java:268)
	at com.ksyun.media.player.KSYMediaPlayer.initPlayer(KSYMediaPlayer.java:398)
	at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:372)
	at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:77)
	at com.ksyun.media.player.KSYMediaPlayer$Builder.build(KSYMediaPlayer.java:340)
	at com.being.fame.ui.activity.play.VideoPlayerBaseActivity.initPlayer(VideoPlayerBaseActivity.java:133)

**Comment by FirmianaRain** [comment]
这个问题暂时未能解决
