### ISSUE TITLE
调用初始化方法报错

### ISSUE THREAD

**Issue by xwlcn** [ksvc/KSYMediaPlayer_Android#67]
Process: com.ksyun.player.demo, PID: 13790
                  java.lang.UnsatisfiedLinkError: No implementation found for void com.ksyun.media.player.KSYMediaPlayer.native_init() (tried Java_com_ksyun_media_player_KSYMediaPlayer_native_1init and Java_com_ksyun_media_player_KSYMediaPlayer_native_1init__)
                      at com.ksyun.media.player.KSYMediaPlayer.native_init(Native Method)
                      at com.ksyun.media.player.KSYMediaPlayer.initNativeOnce(KSYMediaPlayer.java:327)
                      at com.ksyun.media.player.KSYMediaPlayer.b(KSYMediaPlayer.java:421)
                      at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:392)
                      at com.ksyun.media.player.KSYMediaPlayer.<init>(KSYMediaPlayer.java:80)
                      at com.ksyun.media.player.KSYMediaPlayer$Builder.build(KSYMediaPlayer.java:361)
                      at com.ksyun.player.demo.activity.SurfaceActivity.onCreate(SurfaceActivity.java:420)
                      at android.app.Activity.performCreate(Activity.java:5990)

**Comment by FirmianaRain** [comment]
请问是在什么机型上出现这种问题的？

**Comment by xwlcn** [comment]
找到原因了，是模拟器的问题，模拟器是x86处理器，在真机上没问题。

**Comment by xiaochao** [comment]
@FirmianaRain 如果我就想在android studio的x86虚拟机上调试，请问怎么弄了？
