### ISSUE TITLE
 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by sunhonggit** [ksvc/KSYMediaPlayer_Android#84]
I used KSYMediaPlayer play files from local disk, but when my app download files from background, the KSYMediaPlayer occur StackOverflowError? why?

E/AndroidRuntime: FATAL EXCEPTION: Thread-631
                                                                                java.lang.StackOverflowError
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
                                                                                    at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)

**Comment by sunhonggit** [comment]
正常播放一个raw目录下的视频没有问题，只要app在后台线程下载图片的时候，很容易报栈溢出的错误，下载的图片和播放器没有关系，请帮忙看一下是什么问题，谢谢

**Comment by FirmianaRain** [comment]
这是已知问题，新版本会fix，大约这周三能发布

**Comment by sunhonggit** [comment]
您好，请问这个问题的修改方案是否已经提交？

**Comment by FirmianaRain** [comment]
请参考新版本：https://github.com/ksvc/KSYMediaPlayer_Android/releases/tag/v1.7.3
